name: Checkout
on: [workflow_dispatch,push]

jobs:
    checkout-and-dsiplay-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before clone
              run: |
                pwd
                ls -la
            - name: checkout the repository
              uses: actions/checkout@v4
            - name: List the files after repo clone
              run:
               pwd |
               ls -la
