name: Manually Triggered
on:
    workflow_dispatch:
        inputs:
            string:
                description: A string input
                type: string
                required: true
                default: "Default value"
            number:
                description: A number input
                default: 4
                type: number
            option:
                description: "An options input"
                required: true
                default: "Option3"
                type: choice
                options:
                    - Option 1
                    - Option 2
                    - Option 3

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo "$GITHUB_REF"   
            - run: |
                echo "String: ${{ inputs.string }}"
                echo "Number: ${{ inputs.number }}"
                echo "Option: ${{ inputs.option }}"        